/* auto-generated by generate_routes_header.py */

#ifndef _NGX_HTTP_KMP_OUT_API_ROUTES_H_INCLUDED_
#define _NGX_HTTP_KMP_OUT_API_ROUTES_H_INCLUDED_

static ngx_http_api_route_node_t
    ngx_http_kmp_out_api_route_tracks_param_upstreams_param =
{
    NULL,
    NULL,
    NULL,
    &ngx_http_kmp_out_api_upstream_delete,
    NULL,
    NULL,
};


static ngx_http_api_route_child_t
    ngx_http_kmp_out_api_route_tracks_param_upstreams_children[] =
{
    { ngx_string("%"),
        &ngx_http_kmp_out_api_route_tracks_param_upstreams_param },
    { ngx_null_string, NULL },
};


static ngx_http_api_route_node_t
    ngx_http_kmp_out_api_route_tracks_param_upstreams =
{
    ngx_http_kmp_out_api_route_tracks_param_upstreams_children,
    &ngx_http_kmp_out_api_upstreams_get,
    &ngx_http_kmp_out_api_upstreams_list,
    NULL,
    &ngx_http_kmp_out_api_upstreams_post,
    NULL,
};


static ngx_http_api_route_child_t
    ngx_http_kmp_out_api_route_tracks_param_children[] =
{
    { ngx_string("upstreams"),
        &ngx_http_kmp_out_api_route_tracks_param_upstreams },
    { ngx_null_string, NULL },
};


static ngx_int_t ngx_http_kmp_out_api_tracks_param_list(ngx_http_request_t *r,
    ngx_str_t *params, ngx_str_t *response)
{
    ngx_str_set(response, "[\"upstreams\"]");
    return NGX_OK;
}


static ngx_http_api_route_node_t  ngx_http_kmp_out_api_route_tracks_param = {
    ngx_http_kmp_out_api_route_tracks_param_children,
    &ngx_http_kmp_out_api_track_get,
    &ngx_http_kmp_out_api_tracks_param_list,
    NULL,
    NULL,
    NULL,
};


static ngx_http_api_route_child_t
    ngx_http_kmp_out_api_route_tracks_children[] =
{
    { ngx_string("%"), &ngx_http_kmp_out_api_route_tracks_param },
    { ngx_null_string, NULL },
};


static ngx_http_api_route_node_t  ngx_http_kmp_out_api_route_tracks = {
    ngx_http_kmp_out_api_route_tracks_children,
    &ngx_http_kmp_out_api_tracks_get,
    &ngx_http_kmp_out_api_tracks_list,
    NULL,
    NULL,
    NULL,
};


static ngx_http_api_route_child_t  ngx_http_kmp_out_api_route_children[] = {
    { ngx_string("tracks"), &ngx_http_kmp_out_api_route_tracks },
    { ngx_null_string, NULL },
};


static ngx_int_t ngx_http_kmp_out_api_list(ngx_http_request_t *r, ngx_str_t
    *params, ngx_str_t *response)
{
    ngx_str_set(response, "[\"multi\",\"tracks\"]");
    return NGX_OK;
}


static ngx_http_api_route_node_t  ngx_http_kmp_out_api_route = {
    ngx_http_kmp_out_api_route_children,
    &ngx_http_kmp_out_api_get,
    &ngx_http_kmp_out_api_list,
    NULL,
    NULL,
    NULL,
};


#endif /* _NGX_HTTP_KMP_OUT_API_ROUTES_H_INCLUDED_ */
