KSMP_ERR(SUCCESS,                0 )

KSMP_ERR(CHANNEL_NOT_FOUND,      10)
KSMP_ERR(CHANNEL_BLOCKED,        11)

KSMP_ERR(TIMELINE_NOT_FOUND,     20)
KSMP_ERR(TIMELINE_EMPTY,         21)
KSMP_ERR(TIMELINE_EMPTIED,       22)
KSMP_ERR(TIMELINE_EXPIRED,       23)

KSMP_ERR(SEGMENT_NOT_FOUND,      30)
KSMP_ERR(SEGMENT_TIME_NOT_FOUND, 31)
KSMP_ERR(SEGMENT_REMOVED,        32)

KSMP_ERR(VARIANT_NOT_FOUND,      40)
KSMP_ERR(VARIANT_INACTIVE,       41)
KSMP_ERR(VARIANT_NO_MATCH,       42)

KSMP_ERR(MEDIA_INFO_NOT_FOUND,   50)

KSMP_ERR(TRACK_NOT_FOUND,        60)
