# add  for debug:   gdb ../sbin/nginx
ARG ALPINE_VER=3.13.5
FROM alpine:$ALPINE_VER as builder

WORKDIR /tmp

ARG SECURE_TOKEN_MODULE_VERSION=master
ARG AKAMAI_G2O_MODULE_VERSION=master
ARG FFMPEG_VERSION="n4.3.1"

RUN apk add --no-cache --virtual kaltura-deps wget git make cmake yasm zlib-dev alpine-sdk && \
    git clone --branch ${FFMPEG_VERSION}  https://github.com/ffmpeg/ffmpeg.git && \
    cd ffmpeg && ./configure --disable-everything --disable-doc --enable-shared --enable-parser=h264 --enable-decoder=h264 --enable-encoder=jpeg2000 --enable-encoder=jpegls --enable-encoder=ljpeg --enable-encoder=mjpeg && \
    make -j 8 && \
    make install && \
    cd /tmp && \
    git clone --branch ${SECURE_TOKEN_MODULE_VERSION} https://github.com/kaltura/nginx-secure-token-module.git && \
    git clone --branch ${AKAMAI_G2O_MODULE_VERSION} https://github.com/kaltura/nginx_mod_akamai_g2o.git && \
    rm -rf ffmpeg && \
    apk del kaltura-deps

COPY nginx-pckg-module nginx-pckg-module
COPY nginx-common nginx-common