/* auto-generated by generate_json_header.py */

#ifndef ngx_array_entries
#define ngx_array_entries(x)     (sizeof(x) / sizeof(x[0]))
#endif

/* ngx_kmp_rtmp_connect_data_json reader */

typedef struct {
    ngx_str_t  url;
    ngx_str_t  header;
} ngx_kmp_rtmp_connect_data_json_t;


static ngx_json_prop_t  ngx_kmp_rtmp_connect_data_json_url = {
    ngx_string("url"),
    116079ULL,
    NGX_JSON_STRING,
    ngx_json_set_str_slot,
    offsetof(ngx_kmp_rtmp_connect_data_json_t, url),
    NULL
};


static ngx_json_prop_t  ngx_kmp_rtmp_connect_data_json_header = {
    ngx_string("header"),
    3073696397ULL,
    NGX_JSON_STRING,
    ngx_json_set_str_slot,
    offsetof(ngx_kmp_rtmp_connect_data_json_t, header),
    NULL
};


static ngx_json_prop_t  *ngx_kmp_rtmp_connect_data_json[] = {
    &ngx_kmp_rtmp_connect_data_json_url,
    NULL,
    &ngx_kmp_rtmp_connect_data_json_header,
};
