/* auto-generated by generate_routes_header.py */

#ifndef _NGX_HTTP_KMP_RTMP_API_ROUTES_H_INCLUDED_
#define _NGX_HTTP_KMP_RTMP_API_ROUTES_H_INCLUDED_

static ngx_http_api_route_node_t
    ngx_http_kmp_rtmp_api_route_upstreams_param_streams =
{
    NULL,
    &ngx_http_kmp_rtmp_api_streams_get,
    &ngx_http_kmp_rtmp_api_streams_list,
    NULL,
    NULL,
    NULL,
};


static ngx_http_api_route_node_t
    ngx_http_kmp_rtmp_api_route_upstreams_param_tracks_param =
{
    NULL,
    NULL,
    NULL,
    &ngx_http_kmp_rtmp_api_track_delete,
    NULL,
    NULL,
};


static ngx_http_api_route_child_t
    ngx_http_kmp_rtmp_api_route_upstreams_param_tracks_children[] =
{
    { ngx_string("%"),
        &ngx_http_kmp_rtmp_api_route_upstreams_param_tracks_param },
    { ngx_null_string, NULL },
};


static ngx_http_api_route_node_t
    ngx_http_kmp_rtmp_api_route_upstreams_param_tracks =
{
    ngx_http_kmp_rtmp_api_route_upstreams_param_tracks_children,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
};


static ngx_http_api_route_child_t
    ngx_http_kmp_rtmp_api_route_upstreams_param_children[] =
{
    { ngx_string("streams"),
        &ngx_http_kmp_rtmp_api_route_upstreams_param_streams },
    { ngx_string("tracks"),
        &ngx_http_kmp_rtmp_api_route_upstreams_param_tracks },
    { ngx_null_string, NULL },
};


static ngx_int_t ngx_http_kmp_rtmp_api_upstreams_param_list(ngx_http_request_t
    *r, ngx_str_t *params, ngx_str_t *response)
{
    ngx_str_set(response, "[\"streams\",\"tracks\"]");
    return NGX_OK;
}


static ngx_http_api_route_node_t  ngx_http_kmp_rtmp_api_route_upstreams_param =
{
    ngx_http_kmp_rtmp_api_route_upstreams_param_children,
    &ngx_http_kmp_rtmp_api_upstream_get,
    &ngx_http_kmp_rtmp_api_upstreams_param_list,
    &ngx_http_kmp_rtmp_api_upstream_delete,
    NULL,
    NULL,
};


static ngx_http_api_route_child_t
    ngx_http_kmp_rtmp_api_route_upstreams_children[] =
{
    { ngx_string("%"), &ngx_http_kmp_rtmp_api_route_upstreams_param },
    { ngx_null_string, NULL },
};


static ngx_http_api_route_node_t  ngx_http_kmp_rtmp_api_route_upstreams = {
    ngx_http_kmp_rtmp_api_route_upstreams_children,
    &ngx_http_kmp_rtmp_api_upstreams_get,
    &ngx_http_kmp_rtmp_api_upstreams_list,
    NULL,
    NULL,
    NULL,
};


static ngx_http_api_route_child_t  ngx_http_kmp_rtmp_api_route_children[] = {
    { ngx_string("upstreams"), &ngx_http_kmp_rtmp_api_route_upstreams },
    { ngx_null_string, NULL },
};


static ngx_int_t ngx_http_kmp_rtmp_api_list(ngx_http_request_t *r, ngx_str_t
    *params, ngx_str_t *response)
{
    ngx_str_set(response, "[\"multi\",\"upstreams\"]");
    return NGX_OK;
}


static ngx_http_api_route_node_t  ngx_http_kmp_rtmp_api_route = {
    ngx_http_kmp_rtmp_api_route_children,
    &ngx_http_kmp_rtmp_api_get,
    &ngx_http_kmp_rtmp_api_list,
    NULL,
    NULL,
    NULL,
};


#endif /* _NGX_HTTP_KMP_RTMP_API_ROUTES_H_INCLUDED_ */
