/* auto-generated by generate_json_header.py */

#ifndef ngx_array_entries
#define ngx_array_entries(x)     (sizeof(x) / sizeof(x[0]))
#endif

/* ngx_http_pckg_captions_service_json reader */

typedef struct {
    ngx_str_t   label;
    ngx_str_t   lang;
    ngx_flag_t  is_default;
} ngx_http_pckg_captions_service_json_t;


static ngx_json_prop_t  ngx_http_pckg_captions_service_json_label = {
    ngx_string("label"),
    102727412ULL,
    NGX_JSON_STRING,
    ngx_json_set_str_slot,
    offsetof(ngx_http_pckg_captions_service_json_t, label),
    NULL
};


static ngx_json_prop_t  ngx_http_pckg_captions_service_json_lang = {
    ngx_string("lang"),
    3314158ULL,
    NGX_JSON_STRING,
    ngx_json_set_str_slot,
    offsetof(ngx_http_pckg_captions_service_json_t, lang),
    NULL
};


static ngx_json_prop_t  ngx_http_pckg_captions_service_json_is_default = {
    ngx_string("is_default"),
    2876948233633836ULL,
    NGX_JSON_BOOL,
    ngx_json_set_flag_slot,
    offsetof(ngx_http_pckg_captions_service_json_t, is_default),
    NULL
};


static ngx_json_prop_t  *ngx_http_pckg_captions_service_json[] = {
    &ngx_http_pckg_captions_service_json_is_default,
    &ngx_http_pckg_captions_service_json_lang,
    &ngx_http_pckg_captions_service_json_label,
};
