/* auto-generated by generate_json_header.py */

#ifndef ngx_array_entries
#define ngx_array_entries(x)     (sizeof(x) / sizeof(x[0]))
#endif

/* ngx_http_pckg_data_value_json reader */

typedef struct {
    ngx_str_t  id;
    ngx_str_t  value;
    ngx_str_t  uri;
    ngx_str_t  lang;
} ngx_http_pckg_data_value_json_t;


static ngx_json_prop_t  ngx_http_pckg_data_value_json_id = {
    ngx_string("id"),
    3355ULL,
    NGX_JSON_STRING,
    ngx_json_set_str_slot,
    offsetof(ngx_http_pckg_data_value_json_t, id),
    NULL
};


static ngx_json_prop_t  ngx_http_pckg_data_value_json_value = {
    ngx_string("value"),
    111972721ULL,
    NGX_JSON_STRING,
    ngx_json_set_str_slot,
    offsetof(ngx_http_pckg_data_value_json_t, value),
    NULL
};


static ngx_json_prop_t  ngx_http_pckg_data_value_json_uri = {
    ngx_string("uri"),
    116076ULL,
    NGX_JSON_STRING,
    ngx_json_set_str_slot,
    offsetof(ngx_http_pckg_data_value_json_t, uri),
    NULL
};


static ngx_json_prop_t  ngx_http_pckg_data_value_json_lang = {
    ngx_string("lang"),
    3314158ULL,
    NGX_JSON_STRING,
    ngx_json_set_str_slot,
    offsetof(ngx_http_pckg_data_value_json_t, lang),
    NULL
};


static ngx_json_prop_t  *ngx_http_pckg_data_value_json[] = {
    &ngx_http_pckg_data_value_json_uri,
    &ngx_http_pckg_data_value_json_value,
    &ngx_http_pckg_data_value_json_lang,
    &ngx_http_pckg_data_value_json_id,
};
