/* auto-generated by generate_json_builder.py */

#ifndef ngx_copy_fix
#define ngx_copy_fix(dst, src)   ngx_copy(dst, (src), sizeof(src) - 1)
#endif


static size_t
ngx_kmp_push_upstream_republish_json_get_size(ngx_kmp_push_upstream_t *obj)
{
    size_t  result =
        sizeof("\"event_type\":\"republish\",\"id\":\"") - 1 + obj->id.len +
            ngx_escape_json(NULL, obj->id.data, obj->id.len) +
        sizeof("\",\"input_id\":\"") - 1 + obj->track->input_id.len +
            ngx_escape_json(NULL, obj->track->input_id.data,
            obj->track->input_id.len) +
        sizeof("\",\"channel_id\":\"") - 1 + obj->track->channel_id.len +
            ngx_escape_json(NULL, obj->track->channel_id.data,
            obj->track->channel_id.len) +
        sizeof("\",\"track_id\":\"") - 1 + obj->track->track_id.len +
            ngx_escape_json(NULL, obj->track->track_id.data,
            obj->track->track_id.len) +
        sizeof("\"") - 1;

    return result;
}

static u_char *
ngx_kmp_push_upstream_republish_json_write(u_char *p, ngx_kmp_push_upstream_t
    *obj)
{
    p = ngx_copy_fix(p, "\"event_type\":\"republish\",\"id\":\"");
    p = (u_char *) ngx_escape_json(p, obj->id.data, obj->id.len);
    p = ngx_copy_fix(p, "\",\"input_id\":\"");
    p = (u_char *) ngx_escape_json(p, obj->track->input_id.data,
        obj->track->input_id.len);
    p = ngx_copy_fix(p, "\",\"channel_id\":\"");
    p = (u_char *) ngx_escape_json(p, obj->track->channel_id.data,
        obj->track->channel_id.len);
    p = ngx_copy_fix(p, "\",\"track_id\":\"");
    p = (u_char *) ngx_escape_json(p, obj->track->track_id.data,
        obj->track->track_id.len);
    *p++ = '\"';

    return p;
}
