/* auto-generated by generate_routes_header.py */

#ifndef _NGX_RTMP_KMP_API_ROUTES_H_INCLUDED_
#define _NGX_RTMP_KMP_API_ROUTES_H_INCLUDED_

static ngx_http_api_route_node_t  ngx_rtmp_kmp_api_route_sessions_param = {
    NULL,
    NULL,
    &ngx_rtmp_kmp_api_session_delete,
    NULL,
    NULL,
};

static ngx_http_api_route_child_t  ngx_rtmp_kmp_api_route_sessions_children[]
    = {
    { ngx_string("%"), &ngx_rtmp_kmp_api_route_sessions_param },
    { ngx_null_string, NULL },
};

static ngx_http_api_route_node_t  ngx_rtmp_kmp_api_route_sessions = {
    ngx_rtmp_kmp_api_route_sessions_children,
    NULL,
    NULL,
    NULL,
    NULL,
};

static ngx_http_api_route_child_t  ngx_rtmp_kmp_api_route_children[] = {
    { ngx_string("sessions"), &ngx_rtmp_kmp_api_route_sessions },
    { ngx_null_string, NULL },
};

static ngx_http_api_route_node_t  ngx_rtmp_kmp_api_route = {
    ngx_rtmp_kmp_api_route_children,
    &ngx_rtmp_kmp_api_get,
    NULL,
    NULL,
    NULL,
};

#endif /* _NGX_RTMP_KMP_API_ROUTES_H_INCLUDED_ */
