/* auto-generated by generate_json_builder.py */

#ifndef ngx_copy_fix
#define ngx_copy_fix(dst, src)   ngx_copy(dst, (src), sizeof(src) - 1)
#endif


static size_t
ngx_rtmp_kmp_track_rtmp_json_get_size(ngx_rtmp_session_t *obj,
    ngx_rtmp_kmp_publish_t *pi)
{
    size_t  result =
        sizeof("{\"app\":\"") - 1 + obj->app.len + ngx_escape_json(NULL,
            obj->app.data, obj->app.len) +
        sizeof("\",\"flashver\":\"") - 1 + obj->flashver.len +
            ngx_escape_json(NULL, obj->flashver.data, obj->flashver.len) +
        sizeof("\",\"swf_url\":\"") - 1 + obj->swf_url.len +
            ngx_escape_json(NULL, obj->swf_url.data, obj->swf_url.len) +
        sizeof("\",\"tc_url\":\"") - 1 + obj->tc_url.len +
            ngx_escape_json(NULL, obj->tc_url.data, obj->tc_url.len) +
        sizeof("\",\"page_url\":\"") - 1 + obj->page_url.len +
            ngx_escape_json(NULL, obj->page_url.data, obj->page_url.len) +
        sizeof("\",\"addr\":\"") - 1 + obj->connection->addr_text.len +
            ngx_escape_json(NULL, obj->connection->addr_text.data,
            obj->connection->addr_text.len) +
        sizeof("\",\"connection\":") - 1 + NGX_INT_T_LEN +
        sizeof(",\"name\":\"") - 1 + pi->name.len + ngx_escape_json(NULL,
            pi->name.data, pi->name.len) +
        sizeof("\",\"type\":\"") - 1 + pi->type.len + ngx_escape_json(NULL,
            pi->type.data, pi->type.len) +
        sizeof("\",\"args\":\"") - 1 + pi->args.len + ngx_escape_json(NULL,
            pi->args.data, pi->args.len) +
        sizeof("\"}") - 1;

    return result;
}

static u_char *
ngx_rtmp_kmp_track_rtmp_json_write(u_char *p, ngx_rtmp_session_t *obj,
    ngx_rtmp_kmp_publish_t *pi)
{
    p = ngx_copy_fix(p, "{\"app\":\"");
    p = (u_char *) ngx_escape_json(p, obj->app.data, obj->app.len);
    p = ngx_copy_fix(p, "\",\"flashver\":\"");
    p = (u_char *) ngx_escape_json(p, obj->flashver.data, obj->flashver.len);
    p = ngx_copy_fix(p, "\",\"swf_url\":\"");
    p = (u_char *) ngx_escape_json(p, obj->swf_url.data, obj->swf_url.len);
    p = ngx_copy_fix(p, "\",\"tc_url\":\"");
    p = (u_char *) ngx_escape_json(p, obj->tc_url.data, obj->tc_url.len);
    p = ngx_copy_fix(p, "\",\"page_url\":\"");
    p = (u_char *) ngx_escape_json(p, obj->page_url.data, obj->page_url.len);
    p = ngx_copy_fix(p, "\",\"addr\":\"");
    p = (u_char *) ngx_escape_json(p, obj->connection->addr_text.data,
        obj->connection->addr_text.len);
    p = ngx_copy_fix(p, "\",\"connection\":");
    p = ngx_sprintf(p, "%uA", (ngx_atomic_uint_t) obj->connection->number);
    p = ngx_copy_fix(p, ",\"name\":\"");
    p = (u_char *) ngx_escape_json(p, pi->name.data, pi->name.len);
    p = ngx_copy_fix(p, "\",\"type\":\"");
    p = (u_char *) ngx_escape_json(p, pi->type.data, pi->type.len);
    p = ngx_copy_fix(p, "\",\"args\":\"");
    p = (u_char *) ngx_escape_json(p, pi->args.data, pi->args.len);
    p = ngx_copy_fix(p, "\"}");

    return p;
}

static size_t
ngx_rtmp_kmp_track_json_get_size(ngx_rtmp_session_t *obj,
    ngx_rtmp_kmp_publish_t *pi)
{
    size_t  result =
        sizeof("\"input_type\":\"rtmp\",\"rtmp\":") - 1 +
            ngx_rtmp_kmp_track_rtmp_json_get_size(obj, pi);

    return result;
}

static u_char *
ngx_rtmp_kmp_track_json_write(u_char *p, ngx_rtmp_session_t *obj,
    ngx_rtmp_kmp_publish_t *pi)
{
    p = ngx_copy_fix(p, "\"input_type\":\"rtmp\",\"rtmp\":");
    p = ngx_rtmp_kmp_track_rtmp_json_write(p, obj, pi);

    return p;
}
