/* auto-generated by generate_json_builder.py */

#ifndef ngx_copy_fix
#define ngx_copy_fix(dst, src)   ngx_copy(dst, (src), sizeof(src) - 1)
#endif


static size_t
ngx_live_dynamic_var_json_get_size(ngx_live_dynamic_var_t *obj)
{
    size_t  result =
        sizeof("\"") - 1 + obj->value.len + ngx_escape_json(NULL,
            obj->value.data, obj->value.len) +
        sizeof("\"") - 1;

    return result;
}

static u_char *
ngx_live_dynamic_var_json_write(u_char *p, ngx_live_dynamic_var_t *obj)
{
    *p++ = '\"';
    p = (u_char *) ngx_escape_json(p, obj->value.data, obj->value.len);
    *p++ = '\"';

    return p;
}

static size_t
ngx_live_dynamic_vars_json_get_size(ngx_live_dynamic_var_channel_ctx_t *obj)
{
    ngx_queue_t  *q;
    size_t  result =
        sizeof("\"vars\":{") - 1 +
        sizeof("}") - 1;

    for (q = ngx_queue_head(&obj->queue);
        q != ngx_queue_sentinel(&obj->queue);
        q = ngx_queue_next(q))
    {
        ngx_live_dynamic_var_t *cur = ngx_queue_data(q,
            ngx_live_dynamic_var_t, queue);
        result += cur->sn.str.len + ngx_escape_json(NULL, cur->sn.str.data,
            cur->sn.str.len);
        result += ngx_live_dynamic_var_json_get_size(cur) + sizeof(",\"\":") -
            1;
    }

    return result;
}

static u_char *
ngx_live_dynamic_vars_json_write(u_char *p, ngx_live_dynamic_var_channel_ctx_t
    *obj)
{
    ngx_queue_t  *q;
    p = ngx_copy_fix(p, "\"vars\":{");

    for (q = ngx_queue_head(&obj->queue);
        q != ngx_queue_sentinel(&obj->queue);
        q = ngx_queue_next(q))
    {
        ngx_live_dynamic_var_t *cur = ngx_queue_data(q,
            ngx_live_dynamic_var_t, queue);

        if (q != ngx_queue_head(&obj->queue))
        {
            *p++ = ',';
        }
        *p++ = '"';
        p = (u_char *) ngx_escape_json(p, cur->sn.str.data, cur->sn.str.len);
        *p++ = '"';
        *p++ = ':';
        p = ngx_live_dynamic_var_json_write(p, cur);
    }

    *p++ = '}';

    return p;
}
