/* auto-generated by generate_json_header.py */

#ifndef ngx_copy_fix
#define ngx_copy_fix(dst, src)   ngx_copy(dst, (src), sizeof(src) - 1)
#endif

#ifndef ngx_copy_str
#define ngx_copy_str(dst, src)   ngx_copy(dst, (src).data, (src).len)
#endif

/* ngx_live_store_stats_json writer */

size_t
ngx_live_store_stats_json_get_size(ngx_live_store_stats_t *obj)
{
    size_t  result;

    result =
        sizeof("{\"started\":") - 1 + NGX_INT32_LEN +
        sizeof(",\"error\":") - 1 + NGX_INT32_LEN +
        sizeof(",\"success\":") - 1 + NGX_INT32_LEN +
        sizeof(",\"success_msec\":") - 1 + NGX_INT64_LEN +
        sizeof(",\"success_size\":") - 1 + NGX_INT64_LEN +
        sizeof("}") - 1;

    return result;
}


u_char *
ngx_live_store_stats_json_write(u_char *p, ngx_live_store_stats_t *obj)
{
    p = ngx_copy_fix(p, "{\"started\":");
    p = ngx_sprintf(p, "%uD", (uint32_t) obj->started);
    p = ngx_copy_fix(p, ",\"error\":");
    p = ngx_sprintf(p, "%uD", (uint32_t) obj->error);
    p = ngx_copy_fix(p, ",\"success\":");
    p = ngx_sprintf(p, "%uD", (uint32_t) obj->success);
    p = ngx_copy_fix(p, ",\"success_msec\":");
    p = ngx_sprintf(p, "%uL", (uint64_t) obj->success_msec);
    p = ngx_copy_fix(p, ",\"success_size\":");
    p = ngx_sprintf(p, "%uL", (uint64_t) obj->success_size);
    *p++ = '}';

    return p;
}


/* ngx_live_store_json writer */

static size_t
ngx_live_store_json_get_size(void *obj)
{
    size_t  result;

    result =
        sizeof("\"store\":{") - 1 + ngx_live_core_json_get_size(NULL, NULL,
            NGX_LIVE_JSON_CTX_STORE) +
        sizeof("}") - 1;

    return result;
}


static u_char *
ngx_live_store_json_write(u_char *p, void *obj)
{
    p = ngx_copy_fix(p, "\"store\":{");
    p = ngx_live_core_json_write(p, NULL, NULL, NGX_LIVE_JSON_CTX_STORE);
    *p++ = '}';

    return p;
}
