/* auto-generated by generate_json_header.py */

#ifndef ngx_copy_fix
#define ngx_copy_fix(dst, src)   ngx_copy(dst, (src), sizeof(src) - 1)
#endif

/* ngx_live_persist_core_json writer */

size_t
ngx_live_persist_core_json_get_size(ngx_live_persist_file_stats_t *obj)
{
    size_t  result;

    result =
        sizeof("\"pending\":") - 1 + NGX_INT32_LEN +
        sizeof(",\"error\":") - 1 + NGX_INT32_LEN +
        sizeof(",\"success\":") - 1 + NGX_INT32_LEN +
        sizeof(",\"success_msec\":") - 1 + NGX_INT64_LEN +
        sizeof(",\"success_size\":") - 1 + NGX_INT64_LEN;

    return result;
}

u_char *
ngx_live_persist_core_json_write(u_char *p, ngx_live_persist_file_stats_t *obj)
{
    p = ngx_copy_fix(p, "\"pending\":");
    p = ngx_sprintf(p, "%uD", (uint32_t) (obj->started - obj->error -
        obj->success));
    p = ngx_copy_fix(p, ",\"error\":");
    p = ngx_sprintf(p, "%uD", (uint32_t) obj->error);
    p = ngx_copy_fix(p, ",\"success\":");
    p = ngx_sprintf(p, "%uD", (uint32_t) obj->success);
    p = ngx_copy_fix(p, ",\"success_msec\":");
    p = ngx_sprintf(p, "%uL", (uint64_t) obj->success_msec);
    p = ngx_copy_fix(p, ",\"success_size\":");
    p = ngx_sprintf(p, "%uL", (uint64_t) obj->success_size);

    return p;
}

/* ngx_live_persist_setup_obj_json writer */

static size_t
ngx_live_persist_setup_obj_json_get_size(ngx_live_channel_t *obj)
{
    size_t                                result;
    ngx_live_persist_file_stats_t        *stats;
    ngx_live_persist_core_channel_ctx_t  *cctx;

    cctx = ngx_live_get_module_ctx(obj, ngx_live_persist_core_module);
    stats = &cctx->stats[NGX_LIVE_PERSIST_FILE_SETUP];
    result =
        sizeof("{") - 1 + ngx_live_persist_core_json_get_size(stats) +
        sizeof(",") - 1 + ngx_live_persist_setup_json_get_size(obj) +
        sizeof("}") - 1;

    return result;
}

static u_char *
ngx_live_persist_setup_obj_json_write(u_char *p, ngx_live_channel_t *obj)
{
    u_char                               *next;
    ngx_live_persist_file_stats_t        *stats;
    ngx_live_persist_core_channel_ctx_t  *cctx;

    cctx = ngx_live_get_module_ctx(obj, ngx_live_persist_core_module);
    stats = &cctx->stats[NGX_LIVE_PERSIST_FILE_SETUP];
    *p++ = '{';
    p = ngx_live_persist_core_json_write(p, stats);
    *p++ = ',';
    next = ngx_live_persist_setup_json_write(p, obj);
    p = next == p ? p - 1 : next;
    *p++ = '}';

    return p;
}

/* ngx_live_persist_index_obj_json writer */

static size_t
ngx_live_persist_index_obj_json_get_size(ngx_live_channel_t *obj)
{
    size_t                                result;
    ngx_live_persist_file_stats_t        *stats;
    ngx_live_persist_core_channel_ctx_t  *cctx;

    cctx = ngx_live_get_module_ctx(obj, ngx_live_persist_core_module);
    stats = &cctx->stats[NGX_LIVE_PERSIST_FILE_INDEX];
    result =
        sizeof("{") - 1 + ngx_live_persist_core_json_get_size(stats) +
        sizeof(",") - 1 + ngx_live_persist_index_json_get_size(obj) +
        sizeof("}") - 1;

    return result;
}

static u_char *
ngx_live_persist_index_obj_json_write(u_char *p, ngx_live_channel_t *obj)
{
    u_char                               *next;
    ngx_live_persist_file_stats_t        *stats;
    ngx_live_persist_core_channel_ctx_t  *cctx;

    cctx = ngx_live_get_module_ctx(obj, ngx_live_persist_core_module);
    stats = &cctx->stats[NGX_LIVE_PERSIST_FILE_INDEX];
    *p++ = '{';
    p = ngx_live_persist_core_json_write(p, stats);
    *p++ = ',';
    next = ngx_live_persist_index_json_write(p, obj);
    p = next == p ? p - 1 : next;
    *p++ = '}';

    return p;
}

/* ngx_live_persist_delta_obj_json writer */

static size_t
ngx_live_persist_delta_obj_json_get_size(ngx_live_channel_t *obj)
{
    size_t                                result;
    ngx_live_persist_file_stats_t        *stats;
    ngx_live_persist_core_channel_ctx_t  *cctx;

    cctx = ngx_live_get_module_ctx(obj, ngx_live_persist_core_module);
    stats = &cctx->stats[NGX_LIVE_PERSIST_FILE_DELTA];
    result =
        sizeof("{") - 1 + ngx_live_persist_core_json_get_size(stats) +
        sizeof(",") - 1 + ngx_live_persist_delta_json_get_size(obj) +
        sizeof("}") - 1;

    return result;
}

static u_char *
ngx_live_persist_delta_obj_json_write(u_char *p, ngx_live_channel_t *obj)
{
    u_char                               *next;
    ngx_live_persist_file_stats_t        *stats;
    ngx_live_persist_core_channel_ctx_t  *cctx;

    cctx = ngx_live_get_module_ctx(obj, ngx_live_persist_core_module);
    stats = &cctx->stats[NGX_LIVE_PERSIST_FILE_DELTA];
    *p++ = '{';
    p = ngx_live_persist_core_json_write(p, stats);
    *p++ = ',';
    next = ngx_live_persist_delta_json_write(p, obj);
    p = next == p ? p - 1 : next;
    *p++ = '}';

    return p;
}

/* ngx_live_persist_media_obj_json writer */

static size_t
ngx_live_persist_media_obj_json_get_size(ngx_live_channel_t *obj)
{
    size_t                                result;
    ngx_live_persist_file_stats_t        *stats;
    ngx_live_persist_core_channel_ctx_t  *cctx;

    cctx = ngx_live_get_module_ctx(obj, ngx_live_persist_core_module);
    stats = &cctx->stats[NGX_LIVE_PERSIST_FILE_MEDIA];
    result =
        sizeof("{") - 1 + ngx_live_persist_core_json_get_size(stats) +
        sizeof("}") - 1;

    return result;
}

static u_char *
ngx_live_persist_media_obj_json_write(u_char *p, ngx_live_channel_t *obj)
{
    ngx_live_persist_file_stats_t        *stats;
    ngx_live_persist_core_channel_ctx_t  *cctx;

    cctx = ngx_live_get_module_ctx(obj, ngx_live_persist_core_module);
    stats = &cctx->stats[NGX_LIVE_PERSIST_FILE_MEDIA];
    *p++ = '{';
    p = ngx_live_persist_core_json_write(p, stats);
    *p++ = '}';

    return p;
}

/* ngx_live_persist_channel_json writer */

static size_t
ngx_live_persist_channel_json_get_size(void *obj)
{
    size_t  result;

    result =
        sizeof("\"persist\":{\"setup\":") - 1 +
            ngx_live_persist_setup_obj_json_get_size(obj) +
        sizeof(",\"index\":") - 1 +
            ngx_live_persist_index_obj_json_get_size(obj) +
        sizeof(",\"delta\":") - 1 +
            ngx_live_persist_delta_obj_json_get_size(obj) +
        sizeof(",\"media\":") - 1 +
            ngx_live_persist_media_obj_json_get_size(obj) +
        sizeof(",\"media_read\":") - 1 +
            ngx_live_persist_media_read_json_get_size(obj) +
        sizeof("}") - 1;

    return result;
}

static u_char *
ngx_live_persist_channel_json_write(u_char *p, void *obj)
{
    p = ngx_copy_fix(p, "\"persist\":{\"setup\":");
    p = ngx_live_persist_setup_obj_json_write(p, obj);
    p = ngx_copy_fix(p, ",\"index\":");
    p = ngx_live_persist_index_obj_json_write(p, obj);
    p = ngx_copy_fix(p, ",\"delta\":");
    p = ngx_live_persist_delta_obj_json_write(p, obj);
    p = ngx_copy_fix(p, ",\"media\":");
    p = ngx_live_persist_media_obj_json_write(p, obj);
    p = ngx_copy_fix(p, ",\"media_read\":");
    p = ngx_live_persist_media_read_json_write(p, obj);
    *p++ = '}';

    return p;
}
