/* auto-generated by generate_json_header.py */

#ifndef ngx_copy_fix
#define ngx_copy_fix(dst, src)   ngx_copy(dst, (src), sizeof(src) - 1)
#endif

#ifndef ngx_copy_str
#define ngx_copy_str(dst, src)   ngx_copy(dst, (src).data, (src).len)
#endif

/* ngx_live_store_s3_block_json writer */

static size_t
ngx_live_store_s3_block_json_get_size(ngx_live_store_s3_ctx_t *obj)
{
    size_t  result;

    result =
        sizeof("{\"read\":") - 1 +
            ngx_live_store_stats_json_get_size(&obj->read_stats) +
        sizeof(",\"write\":") - 1 +
            ngx_live_store_stats_json_get_size(&obj->write_stats) +
        sizeof("}") - 1;

    return result;
}


static u_char *
ngx_live_store_s3_block_json_write(u_char *p, ngx_live_store_s3_ctx_t *obj)
{
    p = ngx_copy_fix(p, "{\"read\":");
    p = ngx_live_store_stats_json_write(p, &obj->read_stats);
    p = ngx_copy_fix(p, ",\"write\":");
    p = ngx_live_store_stats_json_write(p, &obj->write_stats);
    *p++ = '}';

    return p;
}


/* ngx_live_store_s3_json writer */

static size_t
ngx_live_store_s3_json_get_size(void *obj)
{
    size_t                          result;
    ngx_queue_t                    *q;
    ngx_live_store_s3_ctx_t        *cur;
    ngx_live_store_s3_main_conf_t  *smcf;

    smcf = ngx_live_cycle_get_module_main_conf(ngx_cycle,
        ngx_live_store_s3_module);
    result =
        sizeof("\"s3\":{") - 1 +
        sizeof("}") - 1;

    for (q = ngx_queue_head(&smcf->blocks);
        q != ngx_queue_sentinel(&smcf->blocks);
        q = ngx_queue_next(q))
    {
        cur = ngx_queue_data(q, ngx_live_store_s3_ctx_t, queue);
        result += cur->name.s.len + cur->name.escape;
        result += ngx_live_store_s3_block_json_get_size(cur) +
            sizeof(",\"\":") - 1;
    }

    return result;
}


static u_char *
ngx_live_store_s3_json_write(u_char *p, void *obj)
{
    ngx_queue_t                    *q;
    ngx_live_store_s3_ctx_t        *cur;
    ngx_live_store_s3_main_conf_t  *smcf;

    smcf = ngx_live_cycle_get_module_main_conf(ngx_cycle,
        ngx_live_store_s3_module);
    p = ngx_copy_fix(p, "\"s3\":{");

    for (q = ngx_queue_head(&smcf->blocks);
        q != ngx_queue_sentinel(&smcf->blocks);
        q = ngx_queue_next(q))
    {
        cur = ngx_queue_data(q, ngx_live_store_s3_ctx_t, queue);

        if (p[-1] != '{') {
            *p++ = ',';
        }

        *p++ = '"';
        p = ngx_json_str_write_escape(p, &cur->name.s, cur->name.escape);
        *p++ = '"';
        *p++ = ':';
        p = ngx_live_store_s3_block_json_write(p, cur);
    }

    *p++ = '}';

    return p;
}
