/* auto-generated by generate_routes_header.py */

#ifndef _NGX_HTTP_LIVE_API_ROUTES_H_INCLUDED_
#define _NGX_HTTP_LIVE_API_ROUTES_H_INCLUDED_

static ngx_http_api_route_node_t
    ngx_http_live_api_route_channels_param_timelines_param = {
    NULL,
    &ngx_http_live_api_timeline_get,
    &ngx_http_live_api_timeline_delete,
    NULL,
    &ngx_http_live_api_timeline_put,
};

static ngx_http_api_route_child_t
    ngx_http_live_api_route_channels_param_timelines_children[] = {
    { ngx_string("%"), &ngx_http_live_api_route_channels_param_timelines_param
        },
    { ngx_null_string, NULL },
};

static ngx_http_api_route_node_t
    ngx_http_live_api_route_channels_param_timelines = {
    ngx_http_live_api_route_channels_param_timelines_children,
    &ngx_http_live_api_timelines_get,
    NULL,
    &ngx_http_live_api_timelines_post,
    NULL,
};

static ngx_http_api_route_node_t
    ngx_http_live_api_route_channels_param_variants_param_tracks = {
    NULL,
    NULL,
    NULL,
    &ngx_http_live_api_variant_tracks_post,
    NULL,
};

static ngx_http_api_route_child_t
    ngx_http_live_api_route_channels_param_variants_param_children[] = {
    { ngx_string("tracks"),
        &ngx_http_live_api_route_channels_param_variants_param_tracks },
    { ngx_null_string, NULL },
};

static ngx_http_api_route_node_t
    ngx_http_live_api_route_channels_param_variants_param = {
    ngx_http_live_api_route_channels_param_variants_param_children,
    NULL,
    &ngx_http_live_api_variant_delete,
    NULL,
    NULL,
};

static ngx_http_api_route_child_t
    ngx_http_live_api_route_channels_param_variants_children[] = {
    { ngx_string("%"), &ngx_http_live_api_route_channels_param_variants_param
        },
    { ngx_null_string, NULL },
};

static ngx_http_api_route_node_t
    ngx_http_live_api_route_channels_param_variants = {
    ngx_http_live_api_route_channels_param_variants_children,
    &ngx_http_live_api_variants_get,
    NULL,
    &ngx_http_live_api_variants_post,
    NULL,
};

static ngx_http_api_route_node_t
    ngx_http_live_api_route_channels_param_tracks_param = {
    NULL,
    NULL,
    &ngx_http_live_api_track_delete,
    NULL,
    NULL,
};

static ngx_http_api_route_child_t
    ngx_http_live_api_route_channels_param_tracks_children[] = {
    { ngx_string("%"), &ngx_http_live_api_route_channels_param_tracks_param },
    { ngx_null_string, NULL },
};

static ngx_http_api_route_node_t
    ngx_http_live_api_route_channels_param_tracks = {
    ngx_http_live_api_route_channels_param_tracks_children,
    &ngx_http_live_api_tracks_get,
    NULL,
    &ngx_http_live_api_tracks_post,
    NULL,
};

static ngx_http_api_route_child_t
    ngx_http_live_api_route_channels_param_children[] = {
    { ngx_string("timelines"),
        &ngx_http_live_api_route_channels_param_timelines },
    { ngx_string("variants"), &ngx_http_live_api_route_channels_param_variants
        },
    { ngx_string("tracks"), &ngx_http_live_api_route_channels_param_tracks },
    { ngx_null_string, NULL },
};

static ngx_http_api_route_node_t  ngx_http_live_api_route_channels_param = {
    ngx_http_live_api_route_channels_param_children,
    &ngx_http_live_api_channel_get,
    &ngx_http_live_api_channel_delete,
    NULL,
    &ngx_http_live_api_channel_put,
};

static ngx_http_api_route_child_t  ngx_http_live_api_route_channels_children[]
    = {
    { ngx_string("%"), &ngx_http_live_api_route_channels_param },
    { ngx_null_string, NULL },
};

static ngx_http_api_route_node_t  ngx_http_live_api_route_channels = {
    ngx_http_live_api_route_channels_children,
    &ngx_http_live_api_channels_get,
    NULL,
    &ngx_http_live_api_channels_post,
    NULL,
};

static ngx_http_api_route_child_t  ngx_http_live_api_route_children[] = {
    { ngx_string("channels"), &ngx_http_live_api_route_channels },
    { ngx_null_string, NULL },
};

static ngx_http_api_route_node_t  ngx_http_live_api_route = {
    ngx_http_live_api_route_children,
    &ngx_http_live_api_get,
    NULL,
    NULL,
    NULL,
};

#endif /* _NGX_HTTP_LIVE_API_ROUTES_H_INCLUDED_ */
