/* auto-generated by generate_json_builder.py */

static size_t
ngx_http_live_api_json_get_size(void *obj)
{
    size_t result =
        sizeof("{\"version\":\"") - 1 + ngx_http_live_version.len +
            ngx_escape_json(NULL, ngx_http_live_version.data,
            ngx_http_live_version.len) +
        sizeof("\",\"nginx_version\":\"") - 1 +
            ngx_http_live_nginx_version.len + ngx_escape_json(NULL,
            ngx_http_live_nginx_version.data, ngx_http_live_nginx_version.len)
            +
        sizeof("\",\"compiler\":\"") - 1 + ngx_http_live_compiler.len +
            ngx_escape_json(NULL, ngx_http_live_compiler.data,
            ngx_http_live_compiler.len) +
        sizeof("\",\"built\":\"") - 1 + ngx_http_live_built.len +
            ngx_escape_json(NULL, ngx_http_live_built.data,
            ngx_http_live_built.len) +
        sizeof("\",\"pid\":") - 1 + NGX_INT_T_LEN +
        sizeof(",\"uptime\":") - 1 + NGX_INT_T_LEN +
        sizeof("}") - 1;

    return result;
}

static u_char *
ngx_http_live_api_json_write(u_char *p, void *obj)
{
    p = ngx_copy(p, "{\"version\":\"", sizeof("{\"version\":\"") - 1);
    p = (u_char *) ngx_escape_json(p, ngx_http_live_version.data,
        ngx_http_live_version.len);
    p = ngx_copy(p, "\",\"nginx_version\":\"",
        sizeof("\",\"nginx_version\":\"") - 1);
    p = (u_char *) ngx_escape_json(p, ngx_http_live_nginx_version.data,
        ngx_http_live_nginx_version.len);
    p = ngx_copy(p, "\",\"compiler\":\"", sizeof("\",\"compiler\":\"") - 1);
    p = (u_char *) ngx_escape_json(p, ngx_http_live_compiler.data,
        ngx_http_live_compiler.len);
    p = ngx_copy(p, "\",\"built\":\"", sizeof("\",\"built\":\"") - 1);
    p = (u_char *) ngx_escape_json(p, ngx_http_live_built.data,
        ngx_http_live_built.len);
    p = ngx_copy(p, "\",\"pid\":", sizeof("\",\"pid\":") - 1);
    p = ngx_sprintf(p, "%ui", (ngx_uint_t) ngx_getpid());
    p = ngx_copy(p, ",\"uptime\":", sizeof(",\"uptime\":") - 1);
    p = ngx_sprintf(p, "%i", (ngx_int_t) (ngx_cached_time->sec -
        ngx_http_live_start_time));
    *p++ = '}';

    return p;
}
